# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20170822_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
