# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pwhash',
            new_name='password',
        ),
    ]
